### ISSUE TITLE
Allow for commands on VR join

### ISSUE THREAD

**Issue by HeartlessAUS** [jrbudda/Vivecraft_Spigot_Extensions#69]
Unfortunately spartan's anticheat bypass permissions only work when spartan reloads (no clue why), having commands on player join (with VR) would mean we could force spartan to reload when someone joins, but also send a private message to them, reminding them that VR support is in beta, and to private message a moderator in case of issues.

edit: To add on, I have already contacted Evan (Spartan creator) about the issues as well, the system relies on this way, so it cant be changed.

something like the following:
```
commands:
  enabled: true|false
  vive:
    - 'command one here'
    - 'command two here'
  non-vive:
    - 'command one here'
    - 'command two here'
```

thanks!
